services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672      # AMQP port
      - 15672:15672    # Management UI

  redis:
    image: redis:latest
    ports:
      - 6379:6379
