spring:
  rabbitmq:
    host: localhost
    port: 5672

  main:
    web-application-type: None

rtb:
  exchange:
    bids: bids-exchange
    impressions: impression-exchange

  queue:
    impressions: bidder-1-queue

  routing:
    bids: bids
